# Generated by Django 3.0.8 on 2020-09-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concave_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='date',
            field=models.DateField(default='2000-10-10'),
            preserve_default=False,
        ),
    ]
