# Generated by Django 3.0.8 on 2020-09-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concave_app', '0002_convention_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='location',
            field=models.CharField(default='Chicago, IL', max_length=255),
            preserve_default=False,
        ),
    ]
